spring:
  data:
    mongodb:
      database: testdb
      host: localhost
      port: 27017
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
logging:
  level:
    root: ERROR
server:
  port: 8093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/